#!/bin/bash

# SigmaGPT Free Deployment Guide
echo "🚀 SigmaGPT Free Deployment Instructions"
echo "========================================="
echo ""
echo "🆓 BACKEND: Deploy to Render.com (FREE)"
echo "1. Go to https://render.com"
echo "2. Sign up with GitHub"
echo "3. Click 'New' → 'Web Service'"
echo "4. Connect your GitHub repository"
echo "5. Configure:"
echo "   - Name: sigmagpt-backend"
echo "   - Root directory: Backend"
echo "   - Environment: Node"
echo "   - Build command: npm install"
echo "   - Start command: npm start"
echo "   - Instance type: Free"
echo ""
echo "6. Add environment variables:"
echo "   - USE_PUTER=true"
echo "   - NODE_ENV=production"
echo ""
echo "🆓 FRONTEND: Deploy to Vercel.com (FREE)"
echo "1. Go to https://vercel.com"
echo "2. Import from GitHub"
echo "3. Configure:"
echo "   - Framework: Create React App"
echo "   - Root directory: Frontend"
echo "   - Build command: npm run build"
echo "   - Output directory: build"
echo ""
echo "4. Add environment variable:"
echo "   - REACT_APP_API_URL=https://your-render-backend-url.onrender.com/api"
echo ""
echo "✅ Both platforms offer generous free tiers!"
echo "📝 Total cost: $0/month"