version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - NODE_ENV=production
      - USE_PUTER=true
    ports:
      - target: 3001
        published: 3001